services:
  mysqldb:
    container_name: mysqldb
    restart: always
    image: mysql:9.0.1
    volumes:
      - ./db:/var/lib/mysql
    command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
    environment:
      MYSQL_DATABASE: shop
      MYSQL_ROOT_PASSWORD: admin_password
      TZ: Asia/Seoul
    ports:
      - "3307:3306"
    networks:
      - my-network

networks:
  my-network:
    name: my-network
    driver: bridge